#Date on which the scan will be performed (Mon/Tue/Wed/Thu/Fri/Sat/Sun/Daily). Defaults to 'Sun'
scan_date: 'Mon'

#Time on which the scan will be performed (HH:MM). Defaults to '23:00'
scan_time: "23:00"

#The working folder is the location where the global vulnerability reports file be downloaded,
#and the location when the results of the scan will be stored. Defaults to '/tmp/downloads/'
working_folder: '/tmp/downloads/'

#The name of the global vulnerabilities file as we want to use it localy. Defaults to 'com.redhat.rhsa-all.ds.xml' 
global_vulnerability_file_name: 'com.redhat.rhsa-all.ds.xml'

#Number of times to retry to download the global vulnerabilities report. 
#Standard Interval of 1 minute between retries. Defaults to 3
network_retry: 3

#Webhook where the report will be sent. We send the report.xml file content by default.
#The webhook should be able to handle xml input, via a POST request. Defaults to 'http://localhost:8080' 
webhook: 'https://wslv0000007875.ic.ing.net/test'

#Location of the global vulnerability report. Defaults to the official Red Hat location.
#You can also configure your own location. Basic auth credentials will be used if provided for the download.
vulnerability_report:
  global_vulnerability_report_https_location: 'security/data/metrics/ds/com.redhat.rhsa-all.ds.xml'
  username: ''
  password: ''
  base_vulnerability_report_url: 'https://www.redhat.com/'
