#Date on which the scan will be performed (Mon/Tue/Wed/Thu/Fri/Sat/Sun/Daily). Defaults to 'Sun'
scan_date: "Mon"

#Time on which the scan will be performed (HH:MM). Defaults to '23:00'
scan_time: "23:00"

#The working folder is the location where the global vulnerability reports file be downloaded,
#and the location when the results of the scan will be stored. Defaults to '/tmp/downloads/'
working_folder: "/tmp/downloads/"

#Webhook where the report will be sent. We send the report.xml file content by default.
#The webhook should be able to handle xml input, via a POST request. Defaults to 'http://localhost:8080' 
webhook: "http://localhost:8080"

profile: "xccdf_org.ssgproject.content_profile_C2S"

#whether or not to clean the downloaded and created files after the scan. Defaults to true
clean_files: false

#Location of the global vulnerability report. Defaults to the official Red Hat location.
#You can also configure your own location. Basic auth credentials will be used if provided for the download.
vulnerability_report:
  global_vulnerability_report_https_location: "https://www.redhat.com/security/data/metrics/ds/com.redhat.rhsa-all.ds.xml"
  username: ""
  password: ""

email_config:
  smtp_smarthost: ""
  from: ""
  to: ""
  password: ""
