#Date on which the scan will be performed (Mon/Tue/Wed/Thu/Fri/Sat/Sun/Daily). Defaults to 'Sun'
scan_date: "Mon"

#Time on which the scan will be performed (HH:MM). Defaults to '23:00'
scan_time: "23:00"

#The working folder is the location where the global vulnerability reports file be downloaded,
#and the location when the results of the scan will be stored. Defaults to '/tmp/downloads/'
working_folder: "/tmp/downloads/"

#The name of the global vulnerabilities file as we want to use it localy. Defaults to 'com.redhat.rhsa-all.ds.xml' 
global_vulnerability_file_name: "com.redhat.rhsa-all.ds.xml"

#whether or not to clean the downloaded and created files after the scan. Defaults to true
clean_files: false

#Location of the global vulnerability report. Defaults to the official Red Hat location.
#You can also configure your own location. Basic auth credentials will be used if provided for the download.
vulnerability_report:
  global_vulnerability_report_https_location: "https://www.redhat.com/security/data/metrics/ds/com.redhat.rhsa-all.ds.xml"
  username: ""
  password: ""

